### ISSUE TITLE
Add round-trip testing

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec-tool#47]
The following tests should be added in the CI:

For signing:
- create an ecc key pair
- sign some text with it
- export the public part
- with another command line tool, use the public key and verify the signature

For encryption:
- create a rsa key pair
- export the public part
- encrypt something with the public key with another command
- decrypt with the private key

**Comment by ionut-arm** [comment]
This was partially done in #46 but some work remains on actually verifying the outputs of the commands. 

I've been playing around with `openssl` trying to make it work with our formats but it seems unlikely in our current setup. The problem is that `openssl` likes its public keys encoded in `SubjectPublicKeyInfo` format, while we use different formats for ours. We encode RSA keys in `RSAPublicKey` (which `openssl` could convert using `openssl rsa -RSAPublicKey_in`) and EC keys in SEC 1 format (for which there is no way to convert, I think - not with OpenSSL).

I'll raise a PR to be more specific in the README about what format our public keys are in.

**Comment by ionut-arm** [comment]
> This comments also states that Openssl uses SEC1: https://crypto.stackexchange.com/a/48709

That comment seems to be mostly about private key PEM files (which would also include the public key, I think). I should've "documented" my comment above, I think my understanding was based on stuff like this: https://fm4dd.com/openssl/manual-apps/ec.htm
> This specifies the input format. The DER option with a private key uses an ASN.1 DER encoded SEC1 private key. **When used with a public key it uses the SubjectPublicKeyInfo structur as specified in RFC 3280.**

We should be able to encode ours in a `SubjectPublicKeyInfo`, potentially using [this](https://docs.rs/picky-asn1-x509/0.6.1/picky_asn1_x509/subject_public_key_info/struct.SubjectPublicKeyInfo.html) and having a flag to control in which format we export. Or maybe there's some way to make OpenSSL accept that format for public keys as well. 

Here's another crypto stackexchange comment saying something similar: https://security.stackexchange.com/questions/192720/why-pem-encodings-of-ec-public-and-private-keys-use-different-headers

**Comment by anta5010** [comment]
I've done some digging into public key formats, RFCs and PSA crypto and now I can explain what's wrong with the current implementation of export-public-key in parsec-tool and ask how we should fix it.
  In the explanation below I will use names PKCS1 and PKCS8 for PEM encoded public key formats. PKCS8 name is not strictly correct name because it's a syntax for private keys and not public. But, I don't know and couldn't find a better name and the PKCS8 is anyway widely used on the Internet as a name for public key format defined in https://datatracker.ietf.org/doc/html/rfc3279 and https://datatracker.ietf.org/doc/html/rfc5480. For a short PKCS1 and PKCS8 definitions (and an example of using PKCS8 name for public keys format in ARM Mbed documentation) see https://tls.mbed.org/kb/cryptography/asn1-key-structures-in-der-and-pem
  
  For both RSA and ECC keys export parsec-tool uses the same format with different tag lines "RSA PUBLIC KEY" and "PUBLIC KEY". As a result:

- for RSA keys we get the public key in PKCS1 format which can be ASN.1 parsed or converted by openssl with `-RSAPublicKey_in` parameter:
```
# ./target/debug/parsec-tool export-public-key -k rsa | openssl asn1parse
    0:d=0  hl=4 l= 266 cons: SEQUENCE
    4:d=1  hl=4 l= 257 prim: INTEGER           :DE54D1002B678076DCEF5C735F2D42994C1B4BB6935DAEA34A6AF20BCA59F7E1A2FC4973880856C8F66397AFB315DD6F2A2F61F55E6D0C022ACDA58CA3F9C9833A171E76356291DE67DE3FA600B6536DEB66E17CAC376ABCAA753445CFE2325CA0DCD00CB90815C263A9A9A1BF5656D8FEC874AB7D6534E6912ECE7CD549A3421543D959AC14BAE93188B5FEFAAFF662B52456A64AACEF34277B9E449DA3AA24EED9268740AAD4E02237A0ADCB43A9AA293EDE93424510591DAA6A945C6A811E6F31D88A99E730AF01E8C7E21F7919EF84C2F8876FB8BCB580CAF41003D9E29A5191181450562761BF13071FC2F733684E7F486C824F9A7962661F75B2E712CD
  265:d=1  hl=2 l=   3 prim: INTEGER           :010001

# ./target/debug/parsec-tool export-public-key -k rsa | openssl rsa -pubin -text -noout -RSAPublicKey_in
RSA Public-Key: (2048 bit)
Modulus:
    00:de:54:d1:00:2b:67:80:76:dc:ef:5c:73:5f:2d:
    42:99:4c:1b:4b:b6:93:5d:ae:a3:4a:6a:f2:0b:ca:
    59:f7:e1:a2:fc:49:73:88:08:56:c8:f6:63:97:af:
    b3:15:dd:6f:2a:2f:61:f5:5e:6d:0c:02:2a:cd:a5:
    8c:a3:f9:c9:83:3a:17:1e:76:35:62:91:de:67:de:
    3f:a6:00:b6:53:6d:eb:66:e1:7c:ac:37:6a:bc:aa:
    75:34:45:cf:e2:32:5c:a0:dc:d0:0c:b9:08:15:c2:
    63:a9:a9:a1:bf:56:56:d8:fe:c8:74:ab:7d:65:34:
    e6:91:2e:ce:7c:d5:49:a3:42:15:43:d9:59:ac:14:
    ba:e9:31:88:b5:fe:fa:af:f6:62:b5:24:56:a6:4a:
    ac:ef:34:27:7b:9e:44:9d:a3:aa:24:ee:d9:26:87:
    40:aa:d4:e0:22:37:a0:ad:cb:43:a9:aa:29:3e:de:
    93:42:45:10:59:1d:aa:6a:94:5c:6a:81:1e:6f:31:
    d8:8a:99:e7:30:af:01:e8:c7:e2:1f:79:19:ef:84:
    c2:f8:87:6f:b8:bc:b5:80:ca:f4:10:03:d9:e2:9a:
    51:91:18:14:50:56:27:61:bf:13:07:1f:c2:f7:33:
    68:4e:7f:48:6c:82:4f:9a:79:62:66:1f:75:b2:e7:
    12:cd
Exponent: 65537 (0x10001)
```

- for ECC keys we get a file with incorrect format which can't be parsed or used at all because it's missing algorithm identificator and PKCS1 format can be used for RSA keys only.
```
# ./target/debug/parsec-tool export-public-key -k ecc | openssl asn1parse
Error in encoding
140666925892032:error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long:../crypto/asn1/asn1_lib.c:101:
```

  I've already implemented a change for parsec-tool to optionally export the public keys in PKCS8 format. The format can be used for any types of public keys including RSA and ECC and doesn't require any conversions or special parameters for openssl:
``` 
# ./target/debug/parsec-tool export-public-key -k rsa --pkcs8 | openssl asn1parse
    0:d=0  hl=4 l= 290 cons: SEQUENCE
    4:d=1  hl=2 l=  13 cons: SEQUENCE
    6:d=2  hl=2 l=   9 prim: OBJECT            :rsaEncryption
   17:d=2  hl=2 l=   0 prim: NULL
   19:d=1  hl=4 l= 271 prim: BIT STRING
 
# ./target/debug/parsec-tool export-public-key -k rsa --pkcs8 | openssl rsa -pubin -text -noout
RSA Public-Key: (2048 bit)
Modulus:
    00:de:54:d1:00:2b:67:80:76:dc:ef:5c:73:5f:2d:
    42:99:4c:1b:4b:b6:93:5d:ae:a3:4a:6a:f2:0b:ca:
    59:f7:e1:a2:fc:49:73:88:08:56:c8:f6:63:97:af:
    b3:15:dd:6f:2a:2f:61:f5:5e:6d:0c:02:2a:cd:a5:
    8c:a3:f9:c9:83:3a:17:1e:76:35:62:91:de:67:de:
    3f:a6:00:b6:53:6d:eb:66:e1:7c:ac:37:6a:bc:aa:
    75:34:45:cf:e2:32:5c:a0:dc:d0:0c:b9:08:15:c2:
    63:a9:a9:a1:bf:56:56:d8:fe:c8:74:ab:7d:65:34:
    e6:91:2e:ce:7c:d5:49:a3:42:15:43:d9:59:ac:14:
    ba:e9:31:88:b5:fe:fa:af:f6:62:b5:24:56:a6:4a:
    ac:ef:34:27:7b:9e:44:9d:a3:aa:24:ee:d9:26:87:
    40:aa:d4:e0:22:37:a0:ad:cb:43:a9:aa:29:3e:de:
    93:42:45:10:59:1d:aa:6a:94:5c:6a:81:1e:6f:31:
    d8:8a:99:e7:30:af:01:e8:c7:e2:1f:79:19:ef:84:
    c2:f8:87:6f:b8:bc:b5:80:ca:f4:10:03:d9:e2:9a:
    51:91:18:14:50:56:27:61:bf:13:07:1f:c2:f7:33:
    68:4e:7f:48:6c:82:4f:9a:79:62:66:1f:75:b2:e7:
    12:cd
Exponent: 65537 (0x10001)

# ./target/debug/parsec-tool export-public-key -k ecc --pkcs8 | openssl asn1parse
    0:d=0  hl=2 l=  89 cons: SEQUENCE
    2:d=1  hl=2 l=  19 cons: SEQUENCE
    4:d=2  hl=2 l=   7 prim: OBJECT            :id-ecPublicKey
   13:d=2  hl=2 l=   8 prim: OBJECT            :prime256v1
   23:d=1  hl=2 l=  66 prim: BIT STRING  
 
# ./target/debug/parsec-tool export-public-key -k ecc --pkcs8 | openssl ec -pubin -text -noout
read EC key
Public-Key: (256 bit)
pub:
    04:a7:cb:44:68:ad:6c:e2:19:d0:98:1b:c5:45:74:
    22:52:c8:d4:fa:b1:cd:96:fe:d5:fc:f7:cd:c4:97:
    00:29:c7:25:d5:90:77:0b:f8:b1:23:8a:ca:a4:74:
    57:0a:d5:df:98:59:22:ca:8f:2b:0c:5b:76:9d:3d:
    ee:06:86:a4:93
ASN1 OID: prime256v1
NIST CURVE: P-256
```

Before creating a PR I want to ask public a question. Should PKCS8 format be optional? Is there any reason to keep the default parsec-tool export key behavior? Is the current parsec-tool implementation is used in pipelines which would be broken if we change the default format?
 The options I see are:
 1. Leave the default export format as it is and add optional pkcs8 format
 2. Leave PKCS1 as default for RSA keys and set PKCS8 as default for ECC keys
 3. Change default format to PKCS8 for all types of keys
 4. Change default format to PKCS8 for all types of keys and add optional PKCS1 format for RSA keys.
 
 I personally prefer the third option because:
 - in option 1 we will continue produce useless ECC key export
 - in option 2 we will produce different format of keys which might be confusing for users and using RSA key in PKCS1 format requires either conversion or specific parameters
 - in option 4 the optional PKCS1 format will rarely be used and if required can be converted from PKCS8.

**Comment by hug-dev** [comment]
As discussed [on Slack](https://cloud-native.slack.com/archives/C01EARH2ZB3/p1632314479050900), I think option 4 is good as well :)
