### ISSUE TITLE
Error creating ECC key and signing with RSA key

### ISSUE THREAD

**Issue by vchong** [parallaxsecond/parsec-tool#60]
cc @ruchi393

Hi,

We're testing our implementation of PKCS11 library with `parsec` (service) (`0.7.2` tag) and `parsec-tool` (`0.3.1` tag) and seeing a couple of issues.

1.
```
# parsec-tool create-ecc-key -k tutu
[ERROR parsec_service::providers::pkcs11::key_management] The PKCS11 provider currently only supports creating RSA key pairs.
[ERROR] Subcommand failed: the requested operation or a parameter is not supported by this implementation (ParsecClientError(Service(PsaErrorNotSupported)))
```

But using `pkcs-tool`, we verified that we're able to create ECC keys. Any ideas what might be wrong with the above please?
```
# pkcs11-tool --token-label test-token --pin 123456 --keypairgen --key-type EC:secp384r1 --id 2 --label ecc-key1
Key pair generated:
Private Key Object; EC
  label:      ecc-key1
  ID:         02
  Usage:      sign, derive
  Access:     sensitive, always sensitive, never extractable, local
Public Key Object; EC  EC_POINT 384 bits
  EC_POINT:   046104feed6d490bf1f3662f7f06a9c1fc2b1490e2661aa4a91df019781a9f2c55a052338101ffb33deb1a5ff793bbdecc6f43779297b49f33780792a557ee55dab78922b52b5f29efb30900f801c6f89c0b221439c5c0449f96e4cb7c56222778339f
  EC_PARAMS:  06052b81040022
  label:      ecc-key1
  ID:         02
  Usage:      verify, derive
  Access:     local
```

2.
```
# parsec-tool create-rsa-key -k toto
# parsec-tool sign -k toto "Sign this!"

[ERROR] Key's algorithm is AsymmetricEncryption(RsaPkcs1v15Crypt) which can not be used for signing.
[ERROR] Subcommand failed: They key was not created with the correct algorithm for this operation (ParsecToolError(WrongKeyAlgorithm))
```

I'm not very well-versed in Rust code but looking at https://github.com/parallaxsecond/parsec-tool/blob/0.3.1/src/subcommands/sign.rs, is it right that only signing with ECC keys is supported atm?

**Comment by hug-dev** [comment]
Hello 👋!

First off, really nice key name choice 👌 

For 1, version `7.1` of Parsec does not support creating ECC key on the PKCS11 provider. Since then we added the functionality and if you use version `0.8.0` (which we are currently releasing, it is a release candidate), it should work! I have actually recently updated the Parsec Tool [demo](https://asciinema.org/a/RNPjvbgKDlQ0FRFUUKjjNUom6) which does exactly that.

For 2,

> is it right that only signing with ECC keys is supported atm?

Yes that's correct! For ease of use and to reduce the number of parameters needed, we have restricted signing to ECC keys and encrypting to RSA keys. That's only for Parsec Tool though, with the Rust client you can do whatever you want.
Nothing prevents us to start discussing how we should enable signing for RSA if that's needed!

**Comment by vchong** [comment]
> First off, really nice key name choice ok_hand

Inspired from the demo itself! :wink: 

`0.8.0` works! Thanks a lot!
